
FROM golang:1.20 as build-stage

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY *.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-iris

#Run the test in the container 
FROM build-stage as run-test-stage
RUN go test -v ./... 

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /docker-iris /docker-iris

EXPOSE 8080
USER nonroot:nonroot

ENTRYPOINT [ "/docker-iris" ]