FROM golang:1.21 

WORKDIR /app

COPY go.sum ./app
COPY go.mod  ./app

RUN go mod download

COPY main.go ./app

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-SecondRest

EXPOSE 9003

CMD [ "./docker-SecondRest" ]