FROM golang:latest

WORKDIR /app


COPY go.mod go.sum ./

RUN go mod download

COPY . .
COPY feedback_dir .
RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-feedback

EXPOSE 9004
CMD [ "/docker-feedback" ]
