FROM golang:1.21

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

ARG Default_PORT=9004
ENV PORT=$Default_PORT

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-communication

EXPOSE $Default_PORT
CMD [ "/docker-communication" ]


